export type ColorTypes =
  | 'primary'
  | 'secondary'
  | 'success'
  | 'info'
  | 'warning'
  | 'danger'
  | 'light'
  | 'dark'
  | 'gray.900'
  | 'gray.800'
  | 'gray.700'
  | 'gray.600'
  | 'gray.500'
  | 'gray.400'
  | 'gray.300'
  | 'gray.200'
  | 'gray.100'
  | 'gray.50'

export * from './Box'
export * from './Container'
export * from './Img'
export * from './Spacer'
export * from './Txt'
