export * from './Button'
export * from './Divider'
export * from './Image'
export * from './Text'
export * from './View'

export type ColorTypes =
  | 'primary'
  | 'secondary'
  | 'success'
  | 'info'
  | 'warning'
  | 'danger'
  | 'light'
  | 'dark'
  | 'gray.900'
  | 'gray.800'
  | 'gray.700'
  | 'gray.600'
  | 'gray.500'
  | 'gray.400'
  | 'gray.300'
  | 'gray.200'
  | 'gray.100'
  | 'gray.50'

export type JustifyTypes =
  | 'center'
  | 'flex-start'
  | 'flex-end'
  | 'space-between'
  | 'space-around'
  | 'space-evenly'

export type AlignTypes =
  | 'stretch'
  | 'flex-start'
  | 'flex-end'
  | 'baseline'
  | 'center'
